_config: !include ".hpack.config.yaml"

name:                kupo
version:             2.0.0
stability:           experimental
github:              "cardanosolutions/kupo"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/kupo/tree/master/README.md>
synopsis:            A daemon for building lookup indexes from entities of the Cardano blockchain
category:            Web

extra-source-files:
- db/**/*.sql

data-files:
- docs/openapi.yaml

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

flags:
  production:
    description: Compile executables for production.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  when:
    condition: flag(production)
    ghc-options:
    - -Werror
    - -O2
  dependencies:
    - aeson
    - base16
    - base58-bytestring
    - base64
    - bech32
    - bech32-th
    - binary
    - bytestring
    - cardano-binary
    - cardano-crypto-class
    - cardano-crypto-wrapper
    - cardano-ledger-alonzo
    - cardano-ledger-babbage
    - cardano-ledger-shelley
    - cardano-ledger-shelley-ma
    - cardano-ledger-byron
    - cardano-ledger-core
    - cardano-slotting
    - containers
    - contra-tracer
    - contra-tracers
    - fast-bech32
    - file-embed
    - filepath
    - generic-lens
    - http-client
    - http-types
    - io-classes
    - lens
    - lens-aeson
    - network-mux
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-protocol
    - ouroboros-consensus-shelley
    - ouroboros-network
    - ouroboros-network-framework
    - relude
    - safe
    - safe-exceptions
    - strict-containers
    - sqlite-simple
    - text
    - time
    - transformers
    - typed-protocols
    - unix
    - yaml
    - wai
    - warp
    - websockets
    - websockets-json

tests:
  unit:
    main: Spec.hs
    source-dirs: test
    ghc-options: *ghc-options-test
    dependencies:
    - aeson
    - base
    - bytestring
    - cardano-crypto-class
    - containers
    - directory
    - filepath
    - hspec
    - http-client
    - http-media
    - http-types
    - io-classes
    - io-sim
    - kupo
    - lens-aeson
    - openapi3
    - QuickCheck
    - quickcheck-state-machine
    - relude
    - sqlite-simple
    - temporary
    - text
    - wai
    - wai-extra
    - yaml
    build-tools:
    - hspec-discover

executables:
  kupo:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options-executable
    when:
      condition: flag(production)
      ghc-options:
      - -O2
      - -Werror
      - '"-with-rtsopts=-T -N2 -I0 -A16m"'
    dependencies:
    - kupo
