_config: !include ".hpack.config.yaml"

name:                kupo
version:             0
stability:           stable
github:              "cardanosolutions/kupo"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/kupo/tree/master/README.md>
synopsis:            A daemon for building lookup indexes from entities of the Cardano blockchain
category:            Web

extra-source-files:
- db/**/*.sql

data-files:
- docs/api/*.yaml

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

flags:
  production:
    description: Compile executables for production.
    default: False
    manual: True

  postgres:
    description: Compile for use with a PostgresSQL DB instead of sqlite
    manual: True
    default: False

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  when:
    - condition: flag(postgres)
      then:
        cpp-options: -Dpostgres
        other-modules:
          - Kupo.App.Database.Postgres
      else:
        other-modules:
          - Kupo.App.Database.SQLite
    - condition: flag(production)
      ghc-options:
      - -Wunused-packages
      - -Werror
      - -O2
  dependencies:
    - aeson
    - attoparsec-aeson
    - base16
    - base58-bytestring
    - base64
    - bech32
    - bech32-th
    - binary
    - bytestring
    - cardano-crypto-class
    - cardano-crypto-wrapper
    - cardano-ledger-allegra
    - cardano-ledger-alonzo
    - cardano-ledger-api
    - cardano-ledger-babbage
    - cardano-ledger-binary
    - cardano-ledger-byron
    - cardano-ledger-conway
    - cardano-ledger-core
    - cardano-ledger-mary
    - cardano-ledger-shelley
    - cardano-slotting
    - cardano-strict-containers
    - cborg
    - containers
    - contra-tracer
    - contra-tracers
    - directory
    - fast-bech32
    - file-embed
    - filepath
    - generic-lens
    - http-client
    - http-types
    - io-classes
    - lens
    - lens-aeson
    - modern-uri
    - network-mux
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-consensus-diffusion
    - ouroboros-network
    - ouroboros-network-api
    - ouroboros-network-framework
    - ouroboros-network-protocols
    - prometheus
    - relude
    - resource-pool
    - safe
    - safe-exceptions
    - scientific
    - sqlite-simple
    - template-haskell
    - text
    - text-ansi
    - time
    - transformers
    - typed-protocols
    - unix
    - wai
    - warp
    - websockets
    - websockets-json
    - yaml

tests:
  unit:
    main: Spec.hs
    source-dirs: test
    ghc-options: *ghc-options-test
    dependencies:
    - aeson
    - base
    - bytestring
    - cardano-crypto-class
    - containers
    - directory
    - filepath
    - hspec
    - http-client
    - http-media
    - http-types
    - io-classes
    - io-sim
    - kupo
    - lens-aeson
    - openapi3
    - process
    - QuickCheck
    - quickcheck-state-machine
    - si-timers
    - sqlite-simple
    - stm
    - temporary
    - time
    - transformers
    - text
    - wai
    - wai-extra
    - websockets
    - yaml
    build-tools:
    - hspec-discover

executables:
  kupo:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options-executable
    when:
      - condition: flag(production)
        ghc-options:
        - -O2
        - -Wunused-packages
        - -Werror
        - '"-with-rtsopts=-N -A16m -qb -qg"'
      - condition: flag(postgres)
        cpp-options: -Dpostgres
    dependencies:
    - kupo
